services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=your-secret-jwt-key-change-in-production
      - DB_PATH=/app/data/bowling.db
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8031:80"
    depends_on:
      - backend
    restart: unless-stopped
